### ISSUE TITLE
spago_model.bin conversion failed

### ISSUE THREAD

**Issue by zannet** [nlpodyssey/cybertron#3]
> [root@VM-16-4-centos cybertron]# GOARCH=amd64 CYBERTRON_MODEL=Helsinki-NLP/opus-mt-en-it CYBERTRON_MODELS_DIR=models go run ./examples/textgeneration
> {"level":"debug","file":"models/Helsinki-NLP/opus-mt-en-it/config.json","time":"2022-07-20T10:25:53+08:00","message":"model file already exists, skipping download"}
> {"level":"debug","file":"models/Helsinki-NLP/opus-mt-en-it/pytorch_model.bin","time":"2022-07-20T10:25:53+08:00","message":"model file already exists, skipping download"}
> {"level":"debug","file":"models/Helsinki-NLP/opus-mt-en-it/vocab.json","time":"2022-07-20T10:25:53+08:00","message":"model file already exists, skipping download"}
> {"level":"debug","file":"models/Helsinki-NLP/opus-mt-en-it/source.spm","time":"2022-07-20T10:25:53+08:00","message":"model file already exists, skipping download"}
> {"level":"debug","file":"models/Helsinki-NLP/opus-mt-en-it/target.spm","time":"2022-07-20T10:25:53+08:00","message":"model file already exists, skipping download"}
> Serializing model to "models/Helsinki-NLP/opus-mt-en-it/spago_model.bin"... signal: killed
> 

os: CentOS Linux release 7.9 amd64, go: go1.18.4 linux/amd64, cybertron: latest

spago_model.bin conversion failed with signal killed

**Comment by matteo-grella** [comment]
@zannet RAM?

**Comment by zannet** [comment]
@matteo-grella 4gb, 1.5gb free, how much ram do i need to convert a model

**Comment by zannet** [comment]
problem solved, after expanding ram to 8gb.
